/**
 * Table Column Definitions for Meta Campaigns and Ad Sets.
 */

export const CAMPAIGN_COLUMNS = [
  // IDENTITY
  {
    id: "campaign",
    label: "Campaign Name",
    category: "IDENTITY",
    required: true,
    sortable: true,
    align: "left",
    format: "text",
    defaultVisible: true,
  },
  {
    id: "campaign_status",
    label: "Status",
    category: "IDENTITY",
    required: false,
    sortable: true,
    align: "left",
    format: "status",
    defaultVisible: true,
  },
  {
    id: "campaign_objective",
    label: "Objective",
    category: "IDENTITY",
    required: false,
    sortable: true,
    align: "left",
    format: "text",
    defaultVisible: true,
  },

  // PERFORMANCE
  {
    id: "spend",
    label: "Spend",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "cost_per_result",
    label: "Cost / Result",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "purchases",
    label: "Purchases",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "purchase_conversion_value",
    label: "Purchase Value",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "purchase_roas",
    label: "ROAS",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "roas",
    defaultVisible: true,
  },

  // FUNNEL
  {
    id: "actions_add_to_cart",
    label: "Add to Cart",
    category: "FUNNEL",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "actions_initiate_checkout",
    label: "Checkout Initiated",
    category: "FUNNEL",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },

  // DELIVERY
  {
    id: "reach",
    label: "Reach",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "impressions",
    label: "Impressions",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "ctr",
    label: "CTR",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "percentage",
    defaultVisible: true,
  },
  {
    id: "unique_outbound_clicks_ctr_outbound_click",
    label: "Unique Outbound CTR",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "percentage",
    defaultVisible: true,
  },
  {
    id: "cpc",
    label: "CPC",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "cpm",
    label: "CPM",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "frequency",
    label: "Frequency",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "decimal",
    defaultVisible: true,
  },
];

export const ADSET_COLUMNS = [
  // IDENTITY
  {
    id: "adset_name",
    label: "Ad Set Name",
    category: "IDENTITY",
    required: true,
    sortable: true,
    align: "left",
    format: "text",
    defaultVisible: true,
  },
  {
    id: "campaign",
    label: "Campaign",
    category: "IDENTITY",
    required: false,
    sortable: true,
    align: "left",
    format: "text",
    defaultVisible: true,
  },
  {
    id: "status",
    label: "Status",
    category: "IDENTITY",
    required: false,
    sortable: true,
    align: "left",
    format: "status",
    defaultVisible: true,
  },

  // PERFORMANCE
  {
    id: "spend",
    label: "Spend",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "cost_per_result",
    label: "Cost / Result",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "purchases",
    label: "Purchases",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "purchase_conversion_value",
    label: "Purchase Value",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "purchase_roas",
    label: "ROAS",
    category: "PERFORMANCE",
    required: false,
    sortable: true,
    align: "right",
    format: "roas",
    defaultVisible: true,
  },

  // FUNNEL
  {
    id: "actions_add_to_cart",
    label: "Add to Cart",
    category: "FUNNEL",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "actions_initiate_checkout",
    label: "Checkout Initiated",
    category: "FUNNEL",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },

  // DELIVERY
  {
    id: "reach",
    label: "Reach",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "impressions",
    label: "Impressions",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "clicks",
    label: "Clicks",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "number",
    defaultVisible: true,
  },
  {
    id: "ctr",
    label: "CTR",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "percentage",
    defaultVisible: true,
  },
  {
    id: "unique_outbound_clicks_ctr_outbound_click",
    label: "Unique Outbound CTR",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "percentage",
    defaultVisible: true,
  },
  {
    id: "cpc",
    label: "CPC",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "cpm",
    label: "CPM",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "currency",
    defaultVisible: true,
  },
  {
    id: "frequency",
    label: "Frequency",
    category: "DELIVERY",
    required: false,
    sortable: true,
    align: "right",
    format: "decimal",
    defaultVisible: true,
  },
];
