/**
 * Centralized Authoritative Metric Registry for Vytalis Intelligence (Phase 2 - Task #9).
 * Sole metadata owner for all analytics metrics across Meta, Shopify, Cohorts, Attribution, and Composite.
 *
 * NOTE: This configuration contains DECLARATIVE METADATA ONLY.
 * Executable formulas belong in the Task #10 Formula Registry.
 */

const METRIC_REGISTRY = {
  // =========================================================================
  // META ANALYTICS METRICS
  // =========================================================================
  "meta.spend": {
    id: "meta.spend",
    canonicalName: "Meta Amount Spent",
    displayName: "Amount Spent",
    description: "Total estimated amount of money spent on Meta advertising campaigns.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "No advertising spend occurred in the selected date range",
      nullMeaning: "Spend data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "meta.impressions": {
    id: "meta.impressions",
    canonicalName: "Meta Impressions",
    displayName: "Impressions",
    description: "Total number of times Meta ad creative elements entered a user's screen.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Ads received zero impressions",
      nullMeaning: "Impression data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.reach": {
    id: "meta.reach",
    canonicalName: "Meta Reach",
    displayName: "Reach",
    description: "Estimated number of unique individual Meta accounts that saw your ads at least once.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "non_additive",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero unique users reached",
      nullMeaning: "Reach data unavailable or non-aggregatable across breakdown rows",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.clicks": {
    id: "meta.clicks",
    canonicalName: "Meta Total Clicks",
    displayName: "Clicks",
    description: "Total number of clicks recorded on Meta ads (includes link clicks, post engagements, and profile clicks).",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero ad clicks recorded",
      nullMeaning: "Click data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.ctr": {
    id: "meta.ctr",
    canonicalName: "Meta Click-Through Rate",
    displayName: "CTR",
    description: "Percentage of total ad impressions that resulted in a click (Clicks / Impressions * 100).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.meta.ctr",
    requiredInputs: ["meta.clicks", "meta.impressions"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Impressions occurred but received zero clicks (0.0%)",
      nullMeaning: "Unavailable because impressions equal zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.unique_outbound_ctr": {
    id: "meta.unique_outbound_ctr",
    canonicalName: "Meta Unique Outbound CTR",
    displayName: "Unique Outbound CTR",
    description: "Percentage of unique individuals who clicked an outbound link destination off Meta.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "weighted_average",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero unique outbound clicks occurred",
      nullMeaning: "Unique outbound CTR unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.cpc": {
    id: "meta.cpc",
    canonicalName: "Meta Cost Per Click",
    displayName: "CPC",
    description: "Average cost for each click recorded on Meta ads (Spend / Clicks).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "ratio",
    formulaId: "formula.meta.cpc",
    requiredInputs: ["meta.spend", "meta.clicks"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because zero clicks were recorded",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "advertising_efficiency",
    status: "active",
  },

  "meta.cpm": {
    id: "meta.cpm",
    canonicalName: "Meta Cost Per Thousand Impressions",
    displayName: "CPM",
    description: "Average cost per 1,000 ad impressions (Spend / Impressions * 1000).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "currency_per_thousand",
    valueType: "currency_inr",
    aggregation: "ratio",
    formulaId: "formula.meta.cpm",
    requiredInputs: ["meta.spend", "meta.impressions"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because zero impressions were recorded",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "advertising_efficiency",
    status: "active",
  },

  "meta.frequency": {
    id: "meta.frequency",
    canonicalName: "Meta Ad Frequency",
    displayName: "Frequency",
    description: "Average number of times each unique person saw your Meta ad (Impressions / Reach).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "decimal",
    valueType: "decimal",
    aggregation: "ratio",
    formulaId: "formula.meta.frequency",
    requiredInputs: ["meta.impressions", "meta.reach"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because unique reach is zero or non-aggregatable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "engagement",
    status: "active",
  },

  "meta.purchases": {
    id: "meta.purchases",
    canonicalName: "Meta Pixel Purchases",
    displayName: "Purchases",
    description: "Total count of purchase events attributed to Meta ads by Meta Pixel / Conversions API.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero purchases attributed to Meta ads",
      nullMeaning: "Purchase event data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "conversion",
    status: "active",
  },

  "meta.purchase_value": {
    id: "meta.purchase_value",
    canonicalName: "Meta Purchase Conversion Value",
    displayName: "Purchase Value",
    description: "Total monetary value of purchase conversion events attributed to Meta ads.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero purchase conversion value generated",
      nullMeaning: "Purchase value data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "meta.cpa": {
    id: "meta.cpa",
    canonicalName: "Meta Cost Per Purchase",
    displayName: "Cost per Purchase (CPA)",
    description: "Average ad spend required to generate one purchase on Meta (Spend / Meta Purchases).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "ratio",
    formulaId: "formula.meta.cpa",
    requiredInputs: ["meta.spend", "meta.purchases"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because zero Meta purchases were generated",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "advertising_efficiency",
    status: "active",
  },

  "meta.roas": {
    id: "meta.roas",
    canonicalName: "Meta Return on Ad Spend",
    displayName: "Purchase ROAS",
    description: "Return on ad spend calculated strictly from Meta attributed conversion value (Meta Purchase Value / Meta Spend).",
    platform: "meta",
    source: "calculated",
    type: "derived",
    unit: "ratio",
    valueType: "ratio",
    aggregation: "ratio",
    formulaId: "formula.meta.roas",
    requiredInputs: ["meta.purchase_value", "meta.spend"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Spend occurred but generated 0.0x purchase conversion value",
      nullMeaning: "Unavailable because Meta ad spend equals zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "advertising_efficiency",
    status: "active",
  },

  "meta.add_to_cart": {
    id: "meta.add_to_cart",
    canonicalName: "Meta Add to Cart Events",
    displayName: "Add to Cart",
    description: "Count of Add to Cart events attributed to Meta ads.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero add-to-cart actions recorded",
      nullMeaning: "Add-to-cart data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "conversion",
    status: "active",
  },

  "meta.initiate_checkout": {
    id: "meta.initiate_checkout",
    canonicalName: "Meta Initiate Checkout Events",
    displayName: "Checkout Initiated",
    description: "Count of Initiate Checkout events attributed to Meta ads.",
    platform: "meta",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero checkout initiations recorded",
      nullMeaning: "Checkout initiation data unavailable from provider",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "conversion",
    status: "active",
  },

  // =========================================================================
  // SHOPIFY ANALYTICS METRICS
  // =========================================================================
  "shopify.gross_sales": {
    id: "shopify.gross_sales",
    canonicalName: "Shopify Gross Sales",
    displayName: "Gross Sales",
    description: "Total order line item price before discounts, returns, shipping, and taxes.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero gross sales recorded in the selected date range",
      nullMeaning: "Gross sales data unavailable from store",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.net_sales": {
    id: "shopify.net_sales",
    canonicalName: "Shopify Net Sales",
    displayName: "Net Sales",
    description: "Total sales revenue calculated after applying line item discounts and subtracting returns (Gross Sales - Discounts - Returns).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.net_sales",
    requiredInputs: ["shopify.gross_sales", "shopify.discounts"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero net sales generated in the selected date range",
      nullMeaning: "Net sales data unavailable from store",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.orders_count": {
    id: "shopify.orders_count",
    canonicalName: "Shopify Total Orders",
    displayName: "Total Orders",
    description: "Total number of orders placed in Shopify store within the date range.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero store orders placed",
      nullMeaning: "Order count data unavailable from store",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "sales_volume",
    status: "active",
  },

  "shopify.discounts": {
    id: "shopify.discounts",
    canonicalName: "Shopify Total Discounts",
    displayName: "Total Discounts",
    description: "Total discount amounts applied across all store orders in the date range.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero discounts applied to orders",
      nullMeaning: "Discount data unavailable from store",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.tax": {
    id: "shopify.tax",
    canonicalName: "Shopify Total Taxes",
    displayName: "Total Taxes",
    description: "Total tax amount collected on store orders in the date range.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero tax collected on orders",
      nullMeaning: "Tax data unavailable from store",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.aov": {
    id: "shopify.aov",
    canonicalName: "Shopify Average Order Value",
    displayName: "Average Order Value",
    description: "Date-bounded average net sales generated per store order (Net Sales / Orders Count).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "ratio",
    formulaId: "formula.shopify.aov",
    requiredInputs: ["shopify.net_sales", "shopify.orders_count"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because zero store orders were placed in the date range",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.customer_lifetime_aov": {
    id: "shopify.customer_lifetime_aov",
    canonicalName: "Shopify Customer Lifetime AOV",
    displayName: "Customer Lifetime AOV",
    description: "Lifetime average order value per individual customer account (Total Spent / Orders Count).",
    platform: "shopify",
    source: "windsor",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "weighted_average",
    formulaId: "formula.shopify.customer_lifetime_aov",
    requiredInputs: [],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable for customers with zero past orders",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.prepaid_orders": {
    id: "shopify.prepaid_orders",
    canonicalName: "Shopify Prepaid Orders Count",
    displayName: "Prepaid Orders",
    description: "Count of store orders paid online upfront (Financial Status = PAID).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.prepaid_orders",
    requiredInputs: ["shopify.orders_count"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero prepaid orders placed in date range",
      nullMeaning: "Order payment data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.prepaid_revenue": {
    id: "shopify.prepaid_revenue",
    canonicalName: "Shopify Prepaid Orders Revenue",
    displayName: "Prepaid Revenue",
    description: "Net sales monetary volume generated from upfront prepaid orders.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.prepaid_revenue",
    requiredInputs: ["shopify.net_sales"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero prepaid order revenue generated",
      nullMeaning: "Order payment data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.cod_orders": {
    id: "shopify.cod_orders",
    canonicalName: "Shopify COD Orders Count",
    displayName: "COD Orders",
    description: "Count of Cash on Delivery orders (Financial Status = PENDING / Unpaid).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.cod_orders",
    requiredInputs: ["shopify.orders_count"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero Cash on Delivery orders placed",
      nullMeaning: "Order payment data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.cod_revenue": {
    id: "shopify.cod_revenue",
    canonicalName: "Shopify COD Revenue",
    displayName: "COD Revenue",
    description: "Net sales monetary volume generated from Cash on Delivery orders.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.cod_revenue",
    requiredInputs: ["shopify.net_sales"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero COD revenue generated",
      nullMeaning: "Order payment data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.cancelled_orders": {
    id: "shopify.cancelled_orders",
    canonicalName: "Shopify Cancelled Orders Count",
    displayName: "Cancelled Orders",
    description: "Count of store orders that were cancelled or voided before fulfillment.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.cancelled_orders",
    requiredInputs: ["shopify.orders_count"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero order cancellations occurred",
      nullMeaning: "Cancellation status data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.cancelled_revenue": {
    id: "shopify.cancelled_revenue",
    canonicalName: "Shopify Cancelled Revenue",
    displayName: "Cancelled Revenue",
    description: "Total sales value associated with cancelled store orders.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.cancelled_revenue",
    requiredInputs: ["shopify.net_sales"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero revenue lost to cancellations",
      nullMeaning: "Cancellation status data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.cancellation_rate": {
    id: "shopify.cancellation_rate",
    canonicalName: "Shopify Cancellation Rate",
    displayName: "Cancellation Rate",
    description: "Percentage of total store orders that were cancelled (Cancelled Orders / Total Orders * 100).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.shopify.cancellation_rate",
    requiredInputs: ["shopify.cancelled_orders", "shopify.orders_count"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero cancellations occurred out of placed store orders (0.0%)",
      nullMeaning: "Unavailable because zero store orders were placed in date range",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.cod_cancellation_rate": {
    id: "shopify.cod_cancellation_rate",
    canonicalName: "Shopify COD Cancellation Rate",
    displayName: "COD Cancellation Rate",
    description: "Percentage of Cash on Delivery orders that were cancelled (COD Cancelled Orders / Total COD Orders * 100).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.shopify.cod_cancellation_rate",
    requiredInputs: ["shopify.cod_orders"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero COD orders were cancelled out of placed COD orders (0.0%)",
      nullMeaning: "Unavailable because zero COD orders were placed in date range",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.fulfillment_rate": {
    id: "shopify.fulfillment_rate",
    canonicalName: "Shopify Order Fulfillment Rate",
    displayName: "Fulfillment Rate",
    description: "Percentage of non-cancelled orders that were successfully fulfilled (Fulfilled Non-Cancelled / Total Non-Cancelled * 100).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.shopify.fulfillment_rate",
    requiredInputs: ["shopify.orders_count", "shopify.cancelled_orders"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero non-cancelled orders fulfilled (0.0%)",
      nullMeaning: "Unavailable because zero non-cancelled orders exist in date range",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "order_fulfillment",
    status: "active",
  },

  "shopify.total_customers": {
    id: "shopify.total_customers",
    canonicalName: "Shopify Unique Customers",
    displayName: "Total Customers",
    description: "Count of unique individual customer accounts created or active in Shopify store.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "distinct_count",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero customer accounts found",
      nullMeaning: "Customer dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.single_order_customers": {
    id: "shopify.single_order_customers",
    canonicalName: "Shopify One-Time Customers",
    displayName: "One-Time Customers",
    description: "Count of customers who have placed exactly 1 order in lifetime store history.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.single_order_customers",
    requiredInputs: ["shopify.total_customers"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero one-time buyers found",
      nullMeaning: "Customer dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.repeat_customers": {
    id: "shopify.repeat_customers",
    canonicalName: "Shopify Repeat Customers",
    displayName: "Repeat Customers",
    description: "Count of customers who have placed 2 or more orders in lifetime store history.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.repeat_customers",
    requiredInputs: ["shopify.total_customers"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero repeat buyers found",
      nullMeaning: "Customer dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.repeat_purchase_rate": {
    id: "shopify.repeat_purchase_rate",
    canonicalName: "Shopify Repeat Purchase Rate",
    displayName: "Repeat Purchase Rate",
    description: "Percentage of customer base with 2+ lifetime orders (Repeat Customers / Total Customers * 100).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.shopify.repeat_purchase_rate",
    requiredInputs: ["shopify.repeat_customers", "shopify.total_customers"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero repeat customers exist in customer base (0.0%)",
      nullMeaning: "Unavailable because total customer count is zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.returning_revenue": {
    id: "shopify.returning_revenue",
    canonicalName: "Shopify Returning Customer Revenue",
    displayName: "Returning Revenue",
    description: "Total revenue generated by customers who have placed 2 or more orders.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.returning_revenue",
    requiredInputs: ["shopify.repeat_customers"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero revenue from repeat customers",
      nullMeaning: "Customer dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "financial",
    status: "active",
  },

  "shopify.high_value_threshold": {
    id: "shopify.high_value_threshold",
    canonicalName: "Shopify High-Value Customer Threshold",
    displayName: "High-Value Threshold",
    description: "Minimum lifetime spend required to rank in the top 10% of store customers.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "latest",
    formulaId: "formula.shopify.high_value_threshold",
    requiredInputs: ["shopify.total_customers"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero threshold due to zero positive spend customers",
      nullMeaning: "Customer dataset unavailable",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "customer_analytics",
    status: "active",
  },

  "shopify.product_sales": {
    id: "shopify.product_sales",
    canonicalName: "Shopify Line Item Product Sales",
    displayName: "Product Sales",
    description: "Total monetary volume generated by a specific product line item (Quantity * Price).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.product_sales",
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero product sales generated",
      nullMeaning: "Product sales data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "product_analytics",
    status: "active",
  },

  "shopify.product_orders": {
    id: "shopify.product_orders",
    canonicalName: "Shopify Product Orders Count",
    displayName: "Product Orders",
    description: "Count of distinct store orders containing at least one line item of a specific product.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "distinct_count",
    formulaId: "formula.shopify.product_orders",
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero orders contain this product",
      nullMeaning: "Product order data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "product_analytics",
    status: "active",
  },

  "shopify.share_of_sales": {
    id: "shopify.share_of_sales",
    canonicalName: "Shopify Share of Total Sales",
    displayName: "Share of Sales",
    description: "Percentage contribution of a product or location to total store sales (Entity Sales / Total Sales * 100).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.shopify.share_of_sales",
    requiredInputs: ["shopify.net_sales"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero sales contribution (0.0%)",
      nullMeaning: "Unavailable because total store sales equal zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "product_analytics",
    status: "active",
  },

  "shopify.inventory_units": {
    id: "shopify.inventory_units",
    canonicalName: "Shopify Inventory Quantity",
    displayName: "Inventory Units",
    description: "Current physical stock quantity available for sale in store warehouse.",
    platform: "shopify",
    source: "windsor",
    type: "raw",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: null,
    requiredInputs: [],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Out of Stock (0 units remaining)",
      nullMeaning: "Inventory level data unavailable",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "inventory",
    status: "active",
  },

  "shopify.inventory_retail_value": {
    id: "shopify.inventory_retail_value",
    canonicalName: "Shopify Inventory Retail Value",
    displayName: "Inventory Retail Value",
    description: "Total retail value of current stock on hand (Inventory Units * Unit Retail Price).",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.shopify.inventory_retail_value",
    requiredInputs: ["shopify.inventory_units"],
    directionCategory: "CONTEXTUAL",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero retail value due to 0 inventory units",
      nullMeaning: "Inventory valuation data unavailable",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "inventory",
    status: "active",
  },

  "shopify.low_stock_count": {
    id: "shopify.low_stock_count",
    canonicalName: "Shopify Low Stock SKU Count",
    displayName: "Low Stock SKUs",
    description: "Count of product SKUs with stock level at or below the configured low stock threshold.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.low_stock_count",
    requiredInputs: ["shopify.inventory_units"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero SKUs are in low stock state",
      nullMeaning: "Inventory alert data unavailable",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "inventory",
    status: "active",
  },

  "shopify.out_of_stock_count": {
    id: "shopify.out_of_stock_count",
    canonicalName: "Shopify Out of Stock SKU Count",
    displayName: "Out of Stock SKUs",
    description: "Count of product SKUs with exactly 0 units remaining in stock.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.shopify.out_of_stock_count",
    requiredInputs: ["shopify.inventory_units"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero SKUs are out of stock",
      nullMeaning: "Inventory alert data unavailable",
    },
    dateDependency: {
      isDateDependent: false,
      requiresRange: false,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "inventory",
    status: "active",
  },

  // =========================================================================
  // COHORT ANALYSIS METRICS
  // =========================================================================
  "cohort.size": {
    id: "cohort.size",
    canonicalName: "Cohort Acquisition Size",
    displayName: "Cohort Size",
    description: "Total number of new customers acquired during the initial cohort grouping period.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "count",
    valueType: "integer",
    aggregation: "distinct_count",
    formulaId: "formula.cohort.size",
    requiredInputs: [],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero new customers were acquired in this cohort period",
      nullMeaning: "Cohort initial dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: false,
      supportsCohorts: true,
    },
    timezoneRequirement: "organization_local",
    category: "cohort_retention",
    status: "active",
  },

  "cohort.retention_rate": {
    id: "cohort.retention_rate",
    canonicalName: "Cohort Retention Rate",
    displayName: "Cohort Retention Rate",
    description: "Percentage of initial cohort customers who placed a repeat purchase during an exact elapsed observation period.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "percentage",
    valueType: "percentage",
    aggregation: "ratio",
    formulaId: "formula.cohort.retention_rate",
    requiredInputs: ["cohort.size"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Cohort observation period completed with zero repeat customers (0.0%)",
      nullMeaning: "Observation period is Not Mature (insufficient elapsed observation time)",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: false,
      supportsCohorts: true,
    },
    timezoneRequirement: "organization_local",
    category: "cohort_retention",
    status: "active",
  },

  "cohort.revenue": {
    id: "cohort.revenue",
    canonicalName: "Cohort Repeat Sales Revenue",
    displayName: "Cohort Net Sales",
    description: "Net sales monetary revenue generated by cohort customers during an exact elapsed observation period.",
    platform: "shopify",
    source: "calculated",
    type: "derived",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.cohort.revenue",
    requiredInputs: ["cohort.size"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Cohort observation period completed with ₹0.00 repeat sales revenue",
      nullMeaning: "Observation period is Not Mature (insufficient elapsed observation time)",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: false,
      supportsCohorts: true,
    },
    timezoneRequirement: "organization_local",
    category: "cohort_retention",
    status: "active",
  },

  // =========================================================================
  // ATTRIBUTION & COMPOSITE METRICS
  // =========================================================================
  "attribution.total_orders": {
    id: "attribution.total_orders",
    canonicalName: "Attribution Total Classified Orders",
    displayName: "Attributed Orders",
    description: "Total order volume classified across all 7 attribution channel groups.",
    platform: "attribution",
    source: "composite",
    type: "composite",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.attribution.total_orders",
    requiredInputs: ["shopify.orders_count"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero store orders classified in date range",
      nullMeaning: "Attribution order dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "attribution",
    status: "active",
  },

  "attribution.net_revenue": {
    id: "attribution.net_revenue",
    canonicalName: "Attribution Classified Net Revenue",
    displayName: "Attributed Net Revenue",
    description: "Total net sales monetary volume classified across all 7 attribution channel groups.",
    platform: "attribution",
    source: "composite",
    type: "composite",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "sum",
    formulaId: "formula.attribution.net_revenue",
    requiredInputs: ["shopify.net_sales"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero attributed net revenue generated",
      nullMeaning: "Attribution revenue dataset unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "attribution",
    status: "active",
  },

  "attribution.paid_orders": {
    id: "attribution.paid_orders",
    canonicalName: "Attribution Paid Channels Orders",
    displayName: "Paid Channel Orders",
    description: "Order count classified into Paid Search, Paid Social, or Paid Retargeting channels.",
    platform: "attribution",
    source: "composite",
    type: "composite",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.attribution.paid_orders",
    requiredInputs: ["attribution.total_orders"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero orders attributed to paid marketing channels",
      nullMeaning: "Attribution classification data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "attribution",
    status: "active",
  },

  "attribution.organic_orders": {
    id: "attribution.organic_orders",
    canonicalName: "Attribution Organic & Direct Orders",
    displayName: "Organic & Direct Orders",
    description: "Order count classified into Organic Search, Organic Social, Direct, or Referral channels.",
    platform: "attribution",
    source: "composite",
    type: "composite",
    unit: "count",
    valueType: "integer",
    aggregation: "sum",
    formulaId: "formula.attribution.organic_orders",
    requiredInputs: ["attribution.total_orders"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Zero orders attributed to organic/direct channels",
      nullMeaning: "Attribution classification data unavailable",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "attribution",
    status: "active",
  },

  "composite.blended_roas": {
    id: "composite.blended_roas",
    canonicalName: "Blended Return on Ad Spend",
    displayName: "Blended ROAS",
    description: "Overall marketing efficiency combining total Shopify Net Sales against Meta Ad Spend (Shopify Net Sales / Meta Spend).",
    platform: "composite",
    source: "composite",
    type: "composite",
    unit: "ratio",
    valueType: "ratio",
    aggregation: "ratio",
    formulaId: "formula.composite.blended_roas",
    requiredInputs: ["shopify.net_sales", "meta.spend"],
    directionCategory: "HIGHER_IS_BETTER",
    zeroSemantics: {
      isValidZero: true,
      zeroMeaning: "Meta ad spend occurred but store generated ₹0.00 net sales (0.0x)",
      nullMeaning: "Unavailable because Meta ad spend equals zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "executive_summary",
    status: "active",
  },

  "composite.blended_cac": {
    id: "composite.blended_cac",
    canonicalName: "Blended Customer Acquisition Cost",
    displayName: "Blended CAC",
    description: "Overall marketing cost required to generate one store order (Meta Spend / Total Shopify Orders).",
    platform: "composite",
    source: "composite",
    type: "composite",
    unit: "currency",
    valueType: "currency_inr",
    aggregation: "ratio",
    formulaId: "formula.composite.blended_cac",
    requiredInputs: ["meta.spend", "shopify.orders_count"],
    directionCategory: "LOWER_IS_BETTER",
    zeroSemantics: {
      isValidZero: false,
      zeroMeaning: "Not Applicable",
      nullMeaning: "Unavailable because total store orders equal zero",
    },
    dateDependency: {
      isDateDependent: true,
      requiresRange: true,
      supportsCohorts: false,
    },
    timezoneRequirement: "organization_local",
    category: "executive_summary",
    status: "active",
  },
};

const ALLOWED_PLATFORMS = ["meta", "shopify", "attribution", "composite"];
const ALLOWED_UNITS = ["currency", "count", "percentage", "ratio", "currency_per_thousand", "decimal", "days", "date"];
const ALLOWED_TYPES = ["raw", "derived", "composite"];

/**
 * Validates registry data structure integrity on module initialization.
 */
function validateMetricRegistryIntegrity() {
  const metricKeys = Object.keys(METRIC_REGISTRY);

  metricKeys.forEach((key) => {
    const entry = METRIC_REGISTRY[key];
    if (entry.id !== key) {
      throw new Error(`[Registry Error] Key '${key}' does not match entry id '${entry.id}'`);
    }

    if (!ALLOWED_PLATFORMS.includes(entry.platform)) {
      throw new Error(`[Registry Error] Invalid platform '${entry.platform}' for metric '${key}'`);
    }

    if (!ALLOWED_TYPES.includes(entry.type)) {
      throw new Error(`[Registry Error] Invalid type '${entry.type}' for metric '${key}'`);
    }

    if (!ALLOWED_UNITS.includes(entry.unit)) {
      throw new Error(`[Registry Error] Invalid unit '${entry.unit}' for metric '${key}'`);
    }

    if (entry.type !== "raw" && (!entry.formulaId || typeof entry.formulaId !== "string")) {
      throw new Error(`[Registry Error] Derived/composite metric '${key}' must have a valid formulaId string`);
    }

    if (Array.isArray(entry.requiredInputs)) {
      entry.requiredInputs.forEach((inputId) => {
        if (!METRIC_REGISTRY[inputId]) {
          throw new Error(`[Registry Error] Metric '${key}' references unknown inputId '${inputId}'`);
        }
      });
    }
  });

  return true;
}

// Perform initialization validation
validateMetricRegistryIntegrity();

module.exports = {
  METRIC_REGISTRY,
  ALLOWED_PLATFORMS,
  ALLOWED_UNITS,
  ALLOWED_TYPES,
  validateMetricRegistryIntegrity,
};
