/**
 * Field definitions and configuration for Shopify data endpoints.
 * SOLE OWNER of Shopify Windsor field lists and allowed date presets.
 */

const ALLOWED_SHOPIFY_PRESETS = ["last_7d", "last_30d", "last_90d", "last_year"];

const SHOPIFY_ENDPOINTS = {
  overview: {
    key: "overview",
    adapterMethod: "fetchOverview",
    baseTtl: 300,
    fields: [
      "account_name",
      "shop_name",
      "order_created_at",
      "order_gross_sales",
      "order_net_sales",
      "order_count",
      "order_total_count",
      "order_quantity",
      "order_total_discounts",
      "order_total_tax_amount",
      "order_total_price",
      "order_current_total_price",
      "order_financial_status",
      "order_fully_paid",
      "order_unpaid",
      "order_total_outstanding_amount",
      "order_new_or_returning_customer",
      "order_customer_has_multiple_orders",
    ],
  },
  orders: {
    key: "orders",
    adapterMethod: "fetchOrders",
    baseTtl: 300,
    fields: [
      "account_name",
      "shop_name",
      "order_id",
      "order_name",
      "order_created_at",
      "order_processed_at",
      "order_updated_at",
      "order_customer_id",
      "order_email",
      "order_customer_number_of_orders",
      "order_new_or_returning_customer",
      "order_customer_has_multiple_orders",
      "order_financial_status",
      "order_fulfillment_status",
      "order_fulfillable",
      "order_closed",
      "order_closed_at",
      "order_fully_paid",
      "order_unpaid",
      "order_test",
      "order_gross_sales",
      "order_net_sales",
      "order_subtotal_price",
      "order_current_subtotal_price",
      "order_total_price",
      "order_total_price_amount",
      "order_current_total_price",
      "order_original_price",
      "order_total_discounts",
      "order_current_total_discounts",
      "order_total_tax_amount",
      "order_quantity",
      "order_payment_references",
      "order_total_outstanding_amount",
      "order_total_capturable_amount",
      "order_app_name",
      "order_cancel_reason",
      "order_cancelled_at",
      "order_currency",
      "order_presentment_currency",
    ],
  },
  products: {
    key: "products",
    adapterMethod: "fetchProducts",
    baseTtl: 300,
    fields: [
      "account_name",
      "order_id",
      "order_created_at",
      "line_item__product_id",
      "line_item__name",
      "line_item__title",
      "line_item__quantity",
      "line_item__price",
      "line_item__product_price",
      "line_item__total_discount",
      "line_item__sku",
      "line_item__variant_available_for_sale",
      "line_item__variant_barcode",
      "line_item__variant_compare_at_price",
      "line_item__variant_display_name",
      "variant_title",
      "sku",
    ],
  },
  customers: {
    key: "customers",
    adapterMethod: "fetchCustomers",
    baseTtl: 300,
    fields: [
      "account_name",
      "shop_name",
      "customer_id",
      "customer_email",
      "customer_created_at",
      "customer_updated_at",
      "customer_date",
      "customer_first_name",
      "customer_last_name",
      "customer_state",
      "customer_total_spent",
      "customer_aov",
      "customer_orders_count",
      "customer_verified_email",
      "customer_phone",
      "customer_currency",
      "customer_last_order_id",
      "customer_last_order_name",
      "customer_note",
      "customer_tags",
      "customer_tax_exempt",
    ],
  },
  location: {
    key: "location",
    adapterMethod: "fetchLocation",
    baseTtl: 300,
    fields: [
      "account_name",
      "order_id",
      "order_created_at",
      "order_total_price",
      "order_net_sales",
      "order_quantity",
      "order_shipping_address_city",
      "order_shipping_address_province",
      "order_shipping_address_zip",
    ],
  },
};

const ALLOWED_SHOPIFY_ENDPOINTS = Object.keys(SHOPIFY_ENDPOINTS);

module.exports = {
  ALLOWED_SHOPIFY_PRESETS,
  SHOPIFY_ENDPOINTS,
  ALLOWED_SHOPIFY_ENDPOINTS,
};
